-- MySQL Script generated by MySQL Workbench
-- 05/04/21 00:09:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dbprueba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbprueba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbprueba` DEFAULT CHARACTER SET utf8 ;
USE `dbprueba` ;

-- -----------------------------------------------------
-- Table `dbprueba`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprueba`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(8) NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `fecnac` DATE NULL,
  `telf` INT NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprueba`.`venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprueba`.`venta` (
  `idventa` INT NOT NULL AUTO_INCREMENT,
  `numventa` VARCHAR(45) NOT NULL,
  `montototal` VARCHAR(45) NULL,
  `igv` VARCHAR(45) NULL,
  `fechaventa` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `montobruto` DECIMAL(7,2) NULL,
  `idcliente` INT NOT NULL,
  PRIMARY KEY (`idventa`),
  INDEX `fk_venta_cliente1_idx` (`idcliente` ASC),
  CONSTRAINT `fk_venta_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `dbprueba`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprueba`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprueba`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(80) NULL,
  `stock` DECIMAL(7,2) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dbprueba`.`detalleventa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbprueba`.`detalleventa` (
  `iddetalleventa` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `idventa` INT NOT NULL,
  PRIMARY KEY (`iddetalleventa`),
  INDEX `fk_detalleventa_producto_idx` (`idproducto` ASC),
  INDEX `fk_detalleventa_venta1_idx` (`idventa` ASC),
  CONSTRAINT `fk_detalleventa_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `dbprueba`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalleventa_venta1`
    FOREIGN KEY (`idventa`)
    REFERENCES `dbprueba`.`venta` (`idventa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
